backend:
  name: git-gateway
  branch: master
  commit_messages:
    create: 'Create {{collection}} “{{slug}}”'
    update: 'Update {{collection}} “{{slug}}”'
    delete: 'Delete {{collection}} “{{slug}}”'
    uploadMedia: '[skip ci] Upload “{{path}}”'
    deleteMedia: '[skip ci] Delete “{{path}}”'

media_folder: static/images
public_folder: ../../static/images

collections:
  - name: "blog"
    label: "Blog"
    folder: "content/blog"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Template", name: "template", widget: "hidden", default: "blog-post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "publishedDate", widget: "datetime"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Featured Post", name: "featured", widget: "boolean", default: false}
      - {label: "Featured Image", name: "img", widget: image}
      - {label: "Image Caption", name: "imgAlt", widget: string}
      - {label: "Tags", name: "tags", widget: "list"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "Pages"   
    label: "pages"   
    files:  
      - label: "Home Page"  
        file: "content/home.md"     
        name: "home"           
        fields:  
          - {label: "Home Template", name: "homeTemplate", widget: "hidden", default: "home"}     
          - {label: Title, name: title, widget: string}          
          - {label: Footer Intro Content, name: footerIntroContent, widget: text}
          - {label: International Office Address, name: internationalOfficeAddress, widget: text}
          - {label: International Office Phone, name: internationalOfficePhone, widget: string}
          - {label: International Office Email, name: internationalOfficeEmail, widget: string}
          - {label: Nigeria Office Address, name: nigeriaOfficeAddress, widget: text}
          - {label: Nigeria Office Phone, name: nigeriaOfficePhone, widget: string}
          - {label: Nigeria Office Email, name: nigeriaOfficeEmail, widget: string}
          - label: "Footer Link List" 
            name: "footerLinkList"
            widget: "object"
            fields: 
              - {label: "Link1", name: "link1", widget: "string"}
              - {label: "Link2", name: "link2", widget: "string"}
              - {label: "Link3", name: "link3", widget: "string"}
              - {label: "Link4", name: "link4", widget: "string"}
              - {label: "Link5", name: "link5", widget: "string"}
          - label: "Hero Main heading" 
            name: "heroMainHeading"
            widget: "object"
            fields: 
              - {label: Local, name: heroHeadingLocal, widget: string}
              - {label: Abroad, name: heroMainHeadingAbroad, widget: string}
          - label: "Hero Sub heading" 
            name: "heroSubHeading"
            widget: "object"
            fields: 
              - {label: Local, name: heroSubHeadingLocal, widget: string}
              - {label: Abroad, name: heroSubHeadingAbroad, widget: string}

      - label: "About Page"        
        name: "About"        
        file: "content/about.md"        
        fields:       
          - {label: Title, name: title, widget: string}          
          - {label: Intro text, name: intro, widget: text}          
          - {label: Image, name: image, widget: image}
      - label: "Services Page"        
        name: "Services"        
        file: "content/services.md"        
        fields:       
          - {label: Title, name: title, widget: string}          
          - {label: Intro text, name: intro, widget: text}          
          - {label: Image, name: image, widget: image}
      - label: "FAQ Page"
        name: "faq"
        widget: "object"
        file: "content/faq.md"
        summary: 'Faq Page contents'
        fields:
          - label: "General"
            name: "general"
            widget: "object"
            collapsed: true
            default: true
            fields:
              - label: "How to update my account"
                name: "account"
                widget: "object"
                fields:
                  - {label: "Heading", name: "heading", widget: "string"}
                  - {label: "Text", name: "text", widget: "text"}   
              - label: "How to update my account1"
                name: "account1"
                widget: "object"
                fields:
                  - {label: "Heading", name: "heading", widget: "string"}
                  - {label: "Text", name: "text", widget: "text"} 
              - label: "How to update my account2"
                name: "account2"
                widget: "object"
                fields:
                  - {label: "Heading", name: "heading", widget: "string"}
                  - {label: "Text", name: "text", widget: "text"} 
              - label: "How to update my account3"
                name: "account3"
                widget: "object"
                fields:
                  - {label: "Heading", name: "heading", widget: "string"}
                  - {label: "Text", name: "text", widget: "text"}   
              - label: "How to update my account4"
                name: "account4"
                widget: "object"
                fields:
                  - {label: "Heading", name: "heading", widget: "string"}
                  - {label: "Text", name: "text", widget: "text"} 
              - label: "How to update my account4"
                name: "account5"
                widget: "object"
                fields:
                  - {label: "Heading", name: "heading", widget: "string"}
                  - {label: "Text", name: "text", widget: "text"} 
          - label: "Services"
            name: "services"
            widget: "object"
            collapsed: true
            default: true
            fields:
              - label: "How to update my account"
                name: "account"
                widget: "object"
                fields:
                  - {label: "Heading", name: "heading", widget: "string"}
                  - {label: "Text", name: "text", widget: "text"}   
              - label: "How to update my account1"
                name: "account1"
                widget: "object"
                fields:
                  - {label: "Heading", name: "heading", widget: "string"}
                  - {label: "Text", name: "text", widget: "text"} 
              - label: "How to update my account2"
                name: "account2"
                widget: "object"
                fields:
                  - {label: "Heading", name: "heading", widget: "string"}
                  - {label: "Text", name: "text", widget: "text"} 
              - label: "How to update my account3"
                name: "account3"
                widget: "object"
                fields:
                  - {label: "Heading", name: "heading", widget: "string"}
                  - {label: "Text", name: "text", widget: "text"}   
              - label: "How to update my account4"
                name: "account4"
                widget: "object"
                fields:
                  - {label: "Heading", name: "heading", widget: "string"}
                  - {label: "Text", name: "text", widget: "text"} 
              - label: "How to update my account4"
                name: "account5"
                widget: "object"
                fields:
                  - {label: "Heading", name: "heading", widget: "string"}
                  - {label: "Text", name: "text", widget: "text"} 
          - label: "Payments"
            name: "payments"
            widget: "object"
            collapsed: true
            default: true
            fields:
              - label: "How to send Money baroad"
                name: "account"
                widget: "object"
                fields:
                  - {label: "Heading", name: "heading", widget: "string"}
                  - {label: "Text", name: "text", widget: "text"}   
              - label: "How to update my account1"
                name: "account1"
                widget: "object"
                fields:
                  - {label: "Heading", name: "heading", widget: "string"}
                  - {label: "Text", name: "text", widget: "text"} 
              - label: "How to update my account2"
                name: "account2"
                widget: "object"
                fields:
                  - {label: "Heading", name: "heading", widget: "string"}
                  - {label: "Text", name: "text", widget: "text"} 
              - label: "How to update my account3"
                name: "account3"
                widget: "object"
                fields:
                  - {label: "Heading", name: "heading", widget: "string"}
                  - {label: "Text", name: "text", widget: "text"}   
              - label: "How to update my account4"
                name: "account4"
                widget: "object"
                fields:
                  - {label: "Heading", name: "heading", widget: "string"}
                  - {label: "Text", name: "text", widget: "text"} 
              - label: "How to update my account4"
                name: "account5"
                widget: "object"
                fields:
                  - {label: "Heading", name: "heading", widget: "string"}
                  - {label: "Text", name: "text", widget: "text"} 
          - label: "My Account"
            name: "account"
            widget: "object"
            collapsed: true
            default: true
            fields:
              - label: "How to set up account"
                name: "account"
                widget: "object"
                fields:
                  - {label: "Heading", name: "heading", widget: "string"}
                  - {label: "Text", name: "text", widget: "text"}   
              - label: "How to update my account1"
                name: "account1"
                widget: "object"
                fields:
                  - {label: "Heading", name: "heading", widget: "string"}
                  - {label: "Text", name: "text", widget: "text"} 
              - label: "How to update my account2"
                name: "account2"
                widget: "object"
                fields:
                  - {label: "Heading", name: "heading", widget: "string"}
                  - {label: "Text", name: "text", widget: "text"} 
              - label: "How to update my account3"
                name: "account3"
                widget: "object"
                fields:
                  - {label: "Heading", name: "heading", widget: "string"}
                  - {label: "Text", name: "text", widget: "text"}   
              - label: "How to update my account4"
                name: "account4"
                widget: "object"
                fields:
                  - {label: "Heading", name: "heading", widget: "string"}
                  - {label: "Text", name: "text", widget: "text"} 
              - label: "How to update my account4"
                name: "account5"
                widget: "object"
                fields:
                  - {label: "Heading", name: "heading", widget: "string"}
                  - {label: "Text", name: "text", widget: "text"} 
          - label: "Refund"
            name: "refund"
            widget: "object"
            collapsed: true
            default: true
            fields:
              - label: "How to get refund"
                name: "account"
                widget: "object"
                fields:
                  - {label: "Heading", name: "heading", widget: "string"}
                  - {label: "Text", name: "text", widget: "text"}   
              - label: "How to update my account1"
                name: "account1"
                widget: "object"
                fields:
                  - {label: "Heading", name: "heading", widget: "string"}
                  - {label: "Text", name: "text", widget: "text"} 
              - label: "How to update my account2"
                name: "account2"
                widget: "object"
                fields:
                  - {label: "Heading", name: "heading", widget: "string"}
                  - {label: "Text", name: "text", widget: "text"} 
              - label: "How to update my account3"
                name: "account3"
                widget: "object"
                fields:
                  - {label: "Heading", name: "heading", widget: "string"}
                  - {label: "Text", name: "text", widget: "text"}   
              - label: "How to update my account4"
                name: "account4"
                widget: "object"
                fields:
                  - {label: "Heading", name: "heading", widget: "string"}
                  - {label: "Text", name: "text", widget: "text"} 
              - label: "How to update my account4"
                name: "account5"
                widget: "object"
                fields:
                  - {label: "Heading", name: "heading", widget: "string"}
                  - {label: "Text", name: "text", widget: "text"} 
