backend:
  name: git-gateway
  branch: master
  commit_messages:
    create: 'Create {{collection}} “{{slug}}”'
    update: 'Update {{collection}} “{{slug}}”'
    delete: 'Delete {{collection}} “{{slug}}”'
    uploadMedia: '[skip ci] Upload “{{path}}”'
    deleteMedia: '[skip ci] Delete “{{path}}”'

media_folder: static/images
public_folder: ../../static/images

collections:
  - name: "blog"
    label: "Blog"
    folder: "content/blog"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Template", name: "template", widget: "hidden", default: "blog-post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "publishedDate", widget: "datetime"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Featured Post", name: "featured", widget: "boolean", default: false}
      - {label: "Featured Image", name: "img", widget: image}
      - {label: "Image Caption", name: "imgAlt", widget: string}
      - {label: "Tags", name: "tags", widget: "list"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "Pages"   
    label: "pages"   
    files:  
      - label: "Home Page"  
        file: "content/home.md"     
        name: "home"           
        fields:  
          - {label: "Home Template", name: "homeTemplate", widget: "hidden", default: "home"}     
          - {label: Title, name: title, widget: string}          
          - {label: Intro heading, name: intro, widget: text}   
          - {label: Intro paragraph, name: intro-paragraph, widget: text}                 
          - {label: Main Image1, name: heroMainImage1, widget: image}
          - {label: Payment Image, name: paymentImage, widget: image}
          - {label: Offer Text, name: offerText, widget: string}
          - {label: Consult button, name: consultButtonText, widget: string}
          - {label: Payment Button, name: paymentButtonText, widget: string}
          - {label: Chat Prompt, name: chatPromptText, widget: string}
          - {label: Services, name: servicesHeaderText, widget: string}
          - {label: Services subtext1, name: servicesHeaderText-subtext1, widget: string}
          - {label: Services subtext2, name: servicesHeaderText-subtext2, widget: string}
          - {label: Services subtext3, name: servicesHeaderText-subtext3, widget: string}
          - {label: Services subtext1, name: servicesHeaderText-subtext1-image, widget: image ,required: false}
          - {label: Services subtext2, name: servicesHeaderText-subtext2-image, widget: image,required: false}
          - {label: Services subtext3, name: servicesHeaderText-subtext3-image, widget: image,required: false}
          - {label: Services subtext1 button, name: servicesHeaderText-subtext1-button, widget: string}
          - {label: Services subtext2 button, name: servicesHeaderText-subtext2-button, widget: string}
          - {label: Services subtext3 button, name: servicesHeaderText-subtext3-button, widget: string}
          - {label: Secure heading, name: secureHeading, widget: string}
          - {label: SetUp Image, name: setupImage, widget: image}
          - {label: Secure paragraph, name: secureParagraph, widget: string}
          - {label: Review heading, name: reviewHeading, widget: string}
          - {label: Review paragraph, name: reviewParagraph, widget: string}
          - {label: Coming Soon heading, name: comingSoonHeading, widget: string}
          - {label: Coming Soon paragraph, name: comingSoonParagraph, widget: string}
          - {label: Coming Soon button, name: comingSoonButton, widget: string}
          - {label: Footer heading1, name: footerHeading1, widget: string}
          - {label: Footer heading2, name: footerHeading2, widget: string}
          - {label: Footer heading3, name: footerHeading3, widget: string}
          - {label: Footer Intro, name: footerIntro, widget: text}
          - label: "Footer Link List1" 
            name: "footerLinkList1"
            widget: "object"
            fields: 
              - {label: "Title", name: "title", widget: "string"}
              - {label: "Link", name: "link", widget: "string"}
      - label: "About Page"        
        name: "About"        
        file: "content/about.md"        
        fields:       
          - {label: Title, name: title, widget: string}          
          - {label: Intro text, name: intro, widget: text}          
          - {label: Image, name: image, widget: image}
      - label: "Services Page"        
        name: "Services"        
        file: "content/services.md"        
        fields:       
          - {label: Title, name: title, widget: string}          
          - {label: Intro text, name: intro, widget: text}          
          - {label: Image, name: image, widget: image}
      - label: "FAQ Page"
        name: "faq"
        widget: "object"
        file: "content/faq.md"
        summary: 'Faq Page contents'
        fields:
          - label: "General"
            name: "general"
            widget: "object"
            collapsed: true
            default: true
            fields:
              - label: "How to update my account"
                name: "account"
                widget: "object"
                fields:
                  - {label: "City", name: "city", widget: "string"}
                  - {label: "Postal Code", name: "post-code", widget: "string"}   
              - label: "How to update my account1"
                name: "account1"
                widget: "object"
                fields:
                  - {label: "City", name: "city", widget: "string"}
                  - {label: "Postal Code", name: "post-code", widget: "string"} 
              - label: "How to update my account2"
                name: "account2"
                widget: "object"
                fields:
                  - {label: "City", name: "city", widget: "string"}
                  - {label: "Postal Code", name: "post-code", widget: "string"} 
              - label: "How to update my account3"
                name: "account3"
                widget: "object"
                fields:
                  - {label: "City", name: "city", widget: "string"}
                  - {label: "Postal Code", name: "post-code", widget: "string"}   
              - label: "How to update my account4"
                name: "account4"
                widget: "object"
                fields:
                  - {label: "City", name: "city", widget: "string"}
                  - {label: "Postal Code", name: "post-code", widget: "string"} 
              - label: "How to update my account4"
                name: "account5"
                widget: "object"
                fields:
                  - {label: "City", name: "city", widget: "string"}
                  - {label: "Postal Code", name: "post-code", widget: "string"} 
       