export { ActivitySvgComponent } from './activity'
export { ArrowDownSvgComponent } from './arrow-down'
export { ArrowUpSvgComponent } from './arrow-up'
export { AvatarManSvgComponent } from './avatar-man'
export { AvatarWomanSvgComponent } from './avatar-woman'
export { BackwardSvgComponent } from './backward'
export { CalendarSvgComponent } from './calendar'
export { ChatSvgComponent } from './chat'
export { DashboardSvgComponent } from './dashboard';
export { EasySetUpSvg } from './easy-set-up'
export { FacebookSvgComponent } from './facebook'
export { ForwardSvgComponent } from './forward';
export { HeartSvgComponent } from './heart';
export { HelpSvgComponent } from './help'
export { HistorySvgComponent } from './history';
export { HomeSvgComponent } from './home'
export { InfoSvgComponent } from './info'
export { LockSvgComponent } from './lock'
export { Logo1SvgComponent } from './logo-1'
export { Logo2SvgComponent } from './logo-style-2';
export { MessageSvgComponent } from './message'
export { ProfileSvgComponent } from './profile'
export { SettingsSvgComponent } from './settings';
export { SignOutSvgComponent } from './signOut'
